default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  host: localhost

development:
  <<: *default
  database: to_do_list_development

test:
  <<: *default
  database: to_do_list_test


production:
  <<: *default
  database: to_do_list_production
  username: <%= ENV['YOUR_APP_DATABASE_USERNAME'] %>
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
